spring.application.name=my-spring
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=doudou
spring.datasource.password=1622Val++

spring.jpa.hibernate.ddl-auto=update